name: LON-MIRROR Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -e .

      - name: Run tests (excluding benchmarks)
        run: |
          pytest tests/ -v -m "not benchmark" --cov=omnia --cov-report=term --cov-report=xml

      - name: Run benchmark tests (allowed to fail)
        continue-on-error: true
        run: |
          pytest tests/ -v -m "benchmark"